### ISSUE TITLE
Images don't always show

### ISSUE THREAD

**Issue by foaly-nr1** [lazamar/silver-magpie#1]
The image of [this tweet](https://twitter.com/GIRLBOSS/status/807382200639492097) doesn't show on my timeline as it does for other tweets:

<img width="397" alt="screen shot 2016-12-10 at 19 42 06" src="https://cloud.githubusercontent.com/assets/282458/21075729/ec7da3da-bf10-11e6-9fac-da2af993e9af.png">

**Comment by lazamar** [comment]
Fixed by using API field that shows full tweet text up to 280 characters.
